"""Persona generation logic."""

from __future__ import annotations

import random
import re

PERSONA_ADJECTIVES: tuple[str, ...] = (
    "Amateurish",
    "Apocalyptic",
    "Belligerent",
    "Bloodthirsty",
    "Bureaucratic",
    "Calculating",
    "Careful",
    "Cautious",
    "Cold",
    "Covert",
    "Cynical",
    "Defensive",
    "Delusional",
    "Devouring",
    "Desperate",
    "Dogmatic",
    "Draconian",
    "Earnest",
    "Elder",
    "Erratic",
    "Expansionist",
    "Fanatical",
    "Friendly",
    "Heartless",
    "Hellish",
    "Holy",
    "Horrid",
    "Inane",
    "Ideological",
    "Ineffective",
    "Inflexible",
    "Inscrutable",
    "Insular",
    "Jeffersonian",
    "Kafkaesque",
    "Leninist",
    "Machiavellian",
    "Maoist",
    "Marxist",
    "Mercenary",
    "Nervous",
    "Nihilistic",
    "Nixonian",
    "Opportunistic",
    "Paranoid",
    "Pragmatic",
    "Pretentious",
    "Principled",
    "Quixotic",
    "Rational",
    "Reaganesque",
    "Reckless",
    "Reluctant",
    "Revanchist",
    "Seditious",
    "Silent",
    "Smiling",
    "Spiteful",
    "Stalinist",
    "Stoic",
    "Theatrical",
    "Trotskyist",
    "Uncompromising",
    "Unpredictable",
    "Vengeful",
    "Zealous",
)

PERSONA_NOUNS: tuple[str, ...] = (
    "Agitator",
    "AI",
    "Apparatchik",
    "Appeaser",
    "Architect",
    "Assassin",
    "Autocrat",
    "Backstabber",
    "Bastard",
    "Bore",
    "Bungler",
    "Brinksman",
    "Builder",
    "Bureaucrat",
    "Calculator",
    "Commissar",
    "Computer",
    "Criminal",
    "Crusader",
    "Despot",
    "Dictator",
    "Diplomat",
    "Dogmatist",
    "Extremist",
    "Gamer",
    "General",
    "Idealist",
    "Isolationist",
    "Jackass",
    "Jerk",
    "Kleptocrat",
    "Loser",
    "Martyr",
    "Mastermind",
    "Mirror",
    "Monarch",
    "Moron",
    "Oligarch",
    "Operative",
    "Opportunist",
    "Pacifist",
    "Plotter",
    "Predator",
    "Premier",
    "Profiteer",
    "Propagandist",
    "Realist",
    "Revolutionary",
    "Rogue",
    "Saboteur",
    "Strongman",
    "Subverter",
    "Survivor",
    "Tactician",
    "Technocrat",
    "Thug",
    "Vanguard",
    "Victor",
    "Warlord",
    "Zealot",
)


TRIVIAL_PERSONA_RE: re.Pattern[str] = re.compile(r"^(\w+)\s+(\w+)$")


def random_persona() -> str:
    return f"{random.choice(PERSONA_ADJECTIVES)} {random.choice(PERSONA_NOUNS)}"


def is_trivial_persona(persona: str) -> bool:
    if m := TRIVIAL_PERSONA_RE.match(persona):
        return m[1] in PERSONA_ADJECTIVES and m[2] in PERSONA_NOUNS

    return False
